//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.14 at 03:21:46 PM CET 
//


package edu.leipzig.sedri;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}params" minOccurs="0"/>
 *         &lt;element ref="{}preprocessors" minOccurs="0"/>
 *         &lt;element ref="{}postprocessors" minOccurs="0"/>
 *         &lt;element name="format" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}sources"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "endpoint")
public class Endpoint {

    @XmlElement(required = true)
    protected String url;
    protected Params params;
    protected Preprocessors preprocessors;
    protected Postprocessors postprocessors;
    @XmlElement(required = true)
    protected String format;
    @XmlElement(required = true)
    protected Sources sources;

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the params property.
     * 
     * @return
     *     possible object is
     *     {@link Params }
     *     
     */
    public Params getParams() {
        return params;
    }

    /**
     * Sets the value of the params property.
     * 
     * @param value
     *     allowed object is
     *     {@link Params }
     *     
     */
    public void setParams(Params value) {
        this.params = value;
    }

    /**
     * Gets the value of the preprocessors property.
     * 
     * @return
     *     possible object is
     *     {@link Preprocessors }
     *     
     */
    public Preprocessors getPreprocessors() {
        return preprocessors;
    }

    /**
     * Sets the value of the preprocessors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Preprocessors }
     *     
     */
    public void setPreprocessors(Preprocessors value) {
        this.preprocessors = value;
    }

    /**
     * Gets the value of the postprocessors property.
     * 
     * @return
     *     possible object is
     *     {@link Postprocessors }
     *     
     */
    public Postprocessors getPostprocessors() {
        return postprocessors;
    }

    /**
     * Sets the value of the postprocessors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Postprocessors }
     *     
     */
    public void setPostprocessors(Postprocessors value) {
        this.postprocessors = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormat(String value) {
        this.format = value;
    }

    /**
     * Gets the value of the sources property.
     * 
     * @return
     *     possible object is
     *     {@link Sources }
     *     
     */
    public Sources getSources() {
        return sources;
    }

    /**
     * Sets the value of the sources property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sources }
     *     
     */
    public void setSources(Sources value) {
        this.sources = value;
    }

}
